NAKSHATRA_ATTRIBUTES = {
    "Ashwini": {
        "lord": "Ketu",
        "deity": "Ashwini Kumaras",
        "ganam": "Deva",
        "yoni": "Male Horse",
        "animal": "Horse",
        "tree": "Strychnine Tree",
        "bird": "Hawk",
        "bhutam": "Earth",
    },
    "Bharani": {
        "lord": "Venus",
        "deity": "Yama",
        "ganam": "Manushya",
        "yoni": "Female Elephant",
        "animal": "Elephant",
        "tree": "Amla",
        "bird": "Crow",
        "bhutam": "Fire",
    },
    "Krittika": {
        "lord": "Sun",
        "deity": "Agni",
        "ganam": "Rakshasa",
        "yoni": "Female Sheep",
        "animal": "Sheep",
        "tree": "Fig",
        "bird": "Peacock",
        "bhutam": "Fire",
    },
    "Rohini": {
        "lord": "Moon",
        "deity": "Brahma",
        "ganam": "Manushya",
        "yoni": "Male Serpent",
        "animal": "Serpent",
        "tree": "Jamun",
        "bird": "Owl",
        "bhutam": "Earth",
    },
    "Mrigashirsha": {
        "lord": "Mars",
        "deity": "Soma",
        "ganam": "Deva",
        "yoni": "Female Serpent",
        "animal": "Deer",
        "tree": "Khair",
        "bird": "Sparrow",
        "bhutam": "Earth",
    },
    "Ardra": {
        "lord": "Rahu",
        "deity": "Rudra",
        "ganam": "Manushya",
        "yoni": "Female Dog",
        "animal": "Dog",
        "tree": "Blackberry",
        "bird": "Crow",
        "bhutam": "Air",
    },
    "Punarvasu": {
        "lord": "Jupiter",
        "deity": "Aditi",
        "ganam": "Deva",
        "yoni": "Female Cat",
        "animal": "Cat",
        "tree": "Bamboo",
        "bird": "Swan",
        "bhutam": "Water",
    },
    "Pushya": {
        "lord": "Saturn",
        "deity": "Brihaspati",
        "ganam": "Deva",
        "yoni": "Male Sheep",
        "animal": "Sheep",
        "tree": "Peepal",
        "bird": "Peacock",
        "bhutam": "Water",
    },
    "Ashlesha": {
        "lord": "Mercury",
        "deity": "Nagas",
        "ganam": "Rakshasa",
        "yoni": "Male Cat",
        "animal": "Serpent",
        "tree": "Nagakesar",
        "bird": "Crow",
        "bhutam": "Water",
    },
    "Magha": {
        "lord": "Ketu",
        "deity": "Pitrs",
        "ganam": "Rakshasa",
        "yoni": "Male Rat",
        "animal": "Rat",
        "tree": "Banyan",
        "bird": "Crow",
        "bhutam": "Fire",
    },
    "Purva Phalguni": {
        "lord": "Venus",
        "deity": "Bhaga",
        "ganam": "Manushya",
        "yoni": "Female Rat",
        "animal": "Rat",
        "tree": "Palash",
        "bird": "Crow",
        "bhutam": "Fire",
    },
    "Uttara Phalguni": {
        "lord": "Sun",
        "deity": "Aryaman",
        "ganam": "Manushya",
        "yoni": "Male Cow",
        "animal": "Cow",
        "tree": "Plaksha",
        "bird": "Peacock",
        "bhutam": "Fire",
    },
    "Hasta": {
        "lord": "Moon",
        "deity": "Savitar",
        "ganam": "Deva",
        "yoni": "Female Buffalo",
        "animal": "Buffalo",
        "tree": "Fig Tree",
        "bird": "Crow",
        "bhutam": "Fire",
    },
    "Chitra": {
        "lord": "Mars",
        "deity": "Tvashtar",
        "ganam": "Rakshasa",
        "yoni": "Female Tiger",
        "animal": "Tiger",
        "tree": "Bel",
        "bird": "Peacock",
        "bhutam": "Fire",
    },
    "Swati": {
        "lord": "Rahu",
        "deity": "Vayu",
        "ganam": "Deva",
        "yoni": "Male Buffalo",
        "animal": "Buffalo",
        "tree": "Arjuna",
        "bird": "Swan",
        "bhutam": "Air",
    },
    "Vishakha": {
        "lord": "Jupiter",
        "deity": "Indra–Agni",
        "ganam": "Rakshasa",
        "yoni": "Female Tiger",
        "animal": "Tiger",
        "tree": "Udumbara",
        "bird": "Peacock",
        "bhutam": "Fire",
    },
    "Anuradha": {
        "lord": "Saturn",
        "deity": "Mitra",
        "ganam": "Deva",
        "yoni": "Female Deer",
        "animal": "Deer",
        "tree": "Ashoka",
        "bird": "Swan",
        "bhutam": "Earth",
    },
    "Jyeshtha": {
        "lord": "Mercury",
        "deity": "Indra",
        "ganam": "Rakshasa",
        "yoni": "Male Deer",
        "animal": "Deer",
        "tree": "Neem",
        "bird": "Crow",
        "bhutam": "Earth",
    },
    "Mula": {
        "lord": "Ketu",
        "deity": "Nirriti",
        "ganam": "Rakshasa",
        "yoni": "Male Dog",
        "animal": "Dog",
        "tree": "Bamboo",
        "bird": "Crow",
        "bhutam": "Air",
    },
    "Purva Ashadha": {
        "lord": "Venus",
        "deity": "Apah",
        "ganam": "Manushya",
        "yoni": "Female Monkey",
        "animal": "Monkey",
        "tree": "Peepal",
        "bird": "Swan",
        "bhutam": "Water",
    },
    "Uttara Ashadha": {
        "lord": "Sun",
        "deity": "Vishvedevas",
        "ganam": "Manushya",
        "yoni": "Male Mongoose",
        "animal": "Mongoose",
        "tree": "Jackfruit",
        "bird": "Peacock",
        "bhutam": "Earth",
    },
    "Shravana": {
        "lord": "Moon",
        "deity": "Vishnu",
        "ganam": "Deva",
        "yoni": "Female Monkey",
        "animal": "Monkey",
        "tree": "Ashvattha",
        "bird": "Swan",
        "bhutam": "Air",
    },
    "Dhanishta": {
        "lord": "Mars",
        "deity": "Vasus",
        "ganam": "Rakshasa",
        "yoni": "Female Lion",
        "animal": "Lion",
        "tree": "Shami",
        "bird": "Peacock",
        "bhutam": "Fire",
    },
    "Shatabhisha": {
        "lord": "Rahu",
        "deity": "Varuna",
        "ganam": "Rakshasa",
        "yoni": "Female Horse",
        "animal": "Horse",
        "tree": "Kadamba",
        "bird": "Crow",
        "bhutam": "Air",
    },
    "Purva Bhadrapada": {
        "lord": "Jupiter",
        "deity": "Aja Ekapada",
        "ganam": "Manushya",
        "yoni": "Male Lion",
        "animal": "Lion",
        "tree": "Neem",
        "bird": "Peacock",
        "bhutam": "Fire",
    },
    "Uttara Bhadrapada": {
        "lord": "Saturn",
        "deity": "Ahirbudhnya",
        "ganam": "Manushya",
        "yoni": "Female Cow",
        "animal": "Cow",
        "tree": "Neem",
        "bird": "Swan",
        "bhutam": "Water",
    },
    "Revati": {
        "lord": "Mercury",
        "deity": "Pushan",
        "ganam": "Deva",
        "yoni": "Female Elephant",
        "animal": "Elephant",
        "tree": "Mahua",
        "bird": "Peacock",
        "bhutam": "Water",
    },
}
